# Generated by Django 6.0.2 on 2026-02-21 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_type', models.CharField(choices=[('PNEUMONIA', 'التهاب رئوي'), ('BREAST_CANCER', 'سرطان الثدي'), ('ECG', 'تخطيط القلب'), ('SKIN_CANCER', 'أمراض الجلد'), ('BONE_FRACTURE', 'كسور العظام'), ('BRAIN_TUMOR', 'أورام الدماغ')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medical_uploads/')),
                ('result', models.JSONField(help_text='النتيجة التفصيلية من الذكاء الاصطناعي')),
                ('confidence', models.FloatField(help_text='نسبة دقة التنبؤ')),
                ('ai_advice', models.TextField(blank=True, help_text='النصيحة الطبية المقترحة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
