# Generated by Django 4.2.7 on 2026-02-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_ai', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='نبذة عن الدكتور', null=True),
        ),
    ]
